export const OPENAPI_AUDIENCES = ['consumer', 'first-party', 'callback', 'operator'] as const;

export type OpenApiAudience = typeof OPENAPI_AUDIENCES[number];

/**
 * Documentation audience for every operation published by openapi.ts.
 *
 * Consumer operations are rendered by Mintlify's interactive OpenAPI viewer.
 * Every other operation is rendered in a non-interactive internal inventory.
 * Keep this map exhaustive: generation and tests reject missing or stale IDs.
 */
export const OPENAPI_OPERATION_AUDIENCE: Readonly<Record<string, OpenApiAudience>> = {
  getServiceInfo: 'consumer',
  getHealth: 'consumer',
  getOpenApiDocument: 'consumer',
  getApiReference: 'consumer',
  inspectLandingYouTubeVideo: 'first-party',
  submitScaleInquiry: 'first-party',
  signInWithMagicLink: 'first-party',
  signInWithSocialProvider: 'first-party',
  startDeviceAuthorization: 'consumer',
  exchangeDeviceAuthorization: 'consumer',
  verifyDeviceAuthorization: 'first-party',
  approveDeviceAuthorization: 'first-party',
  denyDeviceAuthorization: 'first-party',
  getAuthSession: 'first-party',
  signOut: 'first-party',
  createApiKey: 'first-party',
  listApiKeys: 'first-party',
  deleteApiKey: 'first-party',
  resolveInput: 'first-party',
  listRecentSources: 'first-party',
  saveRecentSource: 'first-party',
  getRecentSource: 'first-party',
  linkProjectSource: 'first-party',
  getProjectSource: 'first-party',
  openProjectItem: 'first-party',
  pinProjectItemSnapshot: 'first-party',
  startAgentRun: 'consumer',
  getAgentAccess: 'consumer',
  listAgentSessions: 'consumer',
  getAgentSession: 'consumer',
  listAgentSessionAssets: 'consumer',
  getAgentSessionAsset: 'consumer',
  deleteAgentSessionAssets: 'consumer',
  deleteAgentSessionAsset: 'consumer',
  deleteAgentSessionMemory: 'consumer',
  getAgentRun: 'consumer',
  getAgentFramePreview: 'consumer',
  streamAgentRun: 'consumer',
  listAdminAgentTraces:'first-party',
  getAdminAgentTraceRun:'first-party',
  getAdminAgentToolTrace:'first-party',
  exportAdminAgentTrace:'first-party',
  searchPrivateEvidence: 'consumer',
  listProviders: 'consumer',
  searchProvider: 'consumer',
  browseProvider: 'consumer',
  researchTrends: 'consumer',
  generateTrendPlan: 'consumer',
  getVideo: 'consumer',
  getVideoTracks: 'consumer',
  getVideoTranscript: 'consumer',
  getVideoComments: 'consumer',
  getVideoEndscreen: 'consumer',
  getChannel: 'consumer',
  getChannelVideos: 'consumer',
  getChannelPlaylists: 'consumer',
  getPlaylist: 'consumer',
  listProjects: 'consumer',
  createProject: 'consumer',
  getProject: 'consumer',
  deleteProject: 'consumer',
  addProjectItem: 'consumer',
  createImport: 'consumer',
  getJob: 'consumer',
  createAnswer: 'first-party',
  createComparison: 'first-party',
  createReport: 'first-party',
  createProjectExport: 'consumer',
  downloadExport: 'consumer',
  listMonitors: 'consumer',
  createMonitor: 'consumer',
  updateMonitor: 'consumer',
  deleteMonitor: 'consumer',
  listNotifications: 'consumer',
  markNotificationRead: 'consumer',
  getNotificationPreferences: 'consumer',
  updateNotificationPreferences: 'consumer',
  confirmNotificationEmail: 'first-party',
  unsubscribeEmail: 'callback',
  unsubscribeEmailPost: 'callback',
  createYouTubeConnectUrl: 'first-party',
  completeYouTubeOAuth: 'callback',
  disconnectYouTube: 'first-party',
  getBilling: 'first-party',
  getUsage: 'consumer',
  getAdminAccess: 'operator',
  listAgentAccess: 'operator',
  grantAgentAccess: 'operator',
  revokeAgentAccess: 'operator',
  listAdminJobs: 'operator',
  getAdminProxyHealth: 'operator',
  getAccountIdentity: 'consumer',
  deleteAccount: 'first-party',
};

/**
 * Operation-specific cautions for every route excluded from the public playground.
 * Tests keep this inventory aligned with the non-consumer audience map.
 */
export const OPENAPI_INTERNAL_SAFETY: Readonly<Record<string, string>> = {
  createReport: 'Internal research implementation under refinement. Browser-session only; API keys and CLI sessions are rejected. Reserves 40 credits and charges 32 on success.',
  createComparison: 'Internal research implementation under refinement. Browser-session only; API keys and CLI sessions are rejected. Reserves 24 credits and charges 20 on success.',
  createAnswer: 'Internal research implementation under refinement. Browser-session only; API keys and CLI sessions are rejected. Reserves 12 credits and charges 10 on success.',
  listRecentSources: 'Browser-session only. Lists inputs belonging to the authenticated user without exposing shared asset references.',
  saveRecentSource: 'Browser-session only. Resolves existing provider assets server-side; never accepts client-supplied R2 keys or video payloads.',
  getRecentSource: 'Browser-session only. Verifies user ownership before reading the saved shared references.',
  getProjectSource: 'Browser-session only. Verify project ownership and restore the item from that project without modifying saved references.',
  openProjectItem: 'Browser-session only. Verify project and item ownership; restore from storage without provider requests, credits or writes, and only within the user’s saved evidence.',
  pinProjectItemSnapshot: 'Browser-session only. Verify the owned item identity; copy an exact owned Recent or project revision or resolve already-stored data, never client-supplied R2 keys.',
  linkProjectSource: 'Browser-session only. Verify that the project and saved source belong to the same signed-in user before linking shared asset references.',
  inspectLandingYouTubeVideo: 'Public, rate-limited demo route; do not use it as a credentialed bulk-data API.',
  submitScaleInquiry: 'Public lead form; validate Turnstile and rate limits, and never let the caller choose the notification recipient.',
  signInWithMagicLink: 'Sends account email; rate-limit callers and never disclose whether an address is registered.',
  signInWithSocialProvider: 'Starts an interactive browser sign-in; do not call it with API-key credentials.',
  verifyDeviceAuthorization: 'Claims a short-lived user code for the signed-in browser account; show the account and requested access before a decision.',
  approveDeviceAuthorization: 'Issues CLI access after an explicit browser decision; approve only a code the user initiated on a device they control.',
  denyDeviceAuthorization: 'Terminates the pending device request selected by the signed-in user without issuing a credential.',
  getAuthSession: 'Returns the current credential identity; never include raw cookie or bearer material in the response or logs.',
  signOut: 'Revokes the presented session; invoke it only for an explicit logout action and clear the matching local credential after success.',
  createApiKey: 'Creates a secret credential; expose the returned key once and keep it out of logs and client storage.',
  listApiKeys: 'Returns credential metadata; restrict it to the current signed-in account.',
  deleteApiKey: 'Immediately revokes the selected credential; require an explicit user action.',
  resolveInput: 'First-party input router; its dispatch behavior is not a stable public API contract.',
  confirmNotificationEmail: 'Enables email delivery only for the signed-in account after validating the confirmation token.',
  createYouTubeConnectUrl: 'Returns a state-bound OAuth URL; start it only from a user-initiated connection flow.',
  disconnectYouTube: 'Mutates the account connection state; require an explicit user action.',
  getBilling: 'Returns subscription state for the current browser account; do not expose another customer’s provider identifiers.',
  deleteAccount: 'Destructive account operation; require deliberate confirmation and never automate it for a user.',
  unsubscribeEmail: 'A signed link changes email preferences; do not expose or reuse its token.',
  unsubscribeEmailPost: 'Changes email preferences; validate the signed request and avoid logging its token.',
  completeYouTubeOAuth: 'OAuth callback; validate state and consume authorization codes only once.',
  getAdminAccess: 'Checks current operator authorization using a live browser session; does not grant Agent access.',
  listAdminAgentTraces:'Administrative diagnostics across user sessions; require a live verified admin browser session.',
  getAdminAgentTraceRun:'Administrative tool-attempt metadata; require a live verified admin browser session.',
  getAdminAgentToolTrace:'Contains full private tool arguments and results; require a live verified admin browser session and never cache responses.',
  exportAdminAgentTrace:'Downloads private diagnostic payloads; require a live verified admin browser session. Export never executes tools.',
  listAgentAccess: 'Exposes tester email addresses; restrict to authorized operators.',
  grantAgentAccess: 'Grants Agent testing access only; requires an authorized browser session and trusted Origin.',
  revokeAgentAccess: 'Removes Agent access on subsequent requests; requires an explicit operator action and trusted Origin.',
  listAdminJobs: 'May expose cross-account operational metadata; restrict it to authorized operators.',
  getAdminProxyHealth: 'Shows proxy hosts and ports, never credentials; restrict it to authorized operators.',
};
