interface Env {
  BETTER_AUTH_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  YOUTUBE_OAUTH_ENCRYPTION_KEY: string;
  TURNSTILE_SECRET: string;
  POLAR_ACCESS_TOKEN: string;
  POLAR_WEBHOOK_SECRET: string;
  UPSTASH_REDIS_REST_URL: string;
  UPSTASH_REDIS_REST_TOKEN: string;
  LANDING_RATE_LIMIT_SALT: string;
  OUTBOUND_PROXY_URL?: string;
}
