import { AgentAdmissionQueue } from '../agents/runtime/admission-queue';
import type { AgentRequest, AgentAdmission } from '../agents/contracts';
import { DurableObject } from 'cloudflare:workers';
import { z } from 'zod';
import { RECENT_SOURCE_LIMIT, saveReferencedSourceSchema, sourceReferenceSchema, sourceIdentity, sourceIdSchema, sourceRevision, sourceRevisionPayload, sourceRevisionSchema, type RecentSource, type SaveReferencedSource, type SourceReference } from '../lib/source-history';

export type SourceCondition = { sourceId: string; snapshot: SourceReference };

const MAX_SEARCH_TEXT_LENGTH = 32_000;
const MAX_TITLE_LENGTH = 80;
const MAX_PREVIEW_LENGTH = 240;
const MAX_SEARCH_TOKENS = 12;

const recordSessionInputSchema = z.object({
  conversationId: z.string().uuid(),
  runId: z.string().uuid(),
  message: z.string().trim().min(1).max(10_000),
  updatedAt: z.number().int().nonnegative(),
});

const sessionCursorSchema = z.object({
  updatedAt: z.number().int().nonnegative(),
  conversationId: z.string().uuid(),
});

const listSessionsInputSchema = z.object({
  query: z.string().trim().max(200).optional(),
  limit: z.number().int().min(1).max(100).default(20),
  cursor: sessionCursorSchema.optional(),
});

export type RecordSessionInput = z.infer<typeof recordSessionInputSchema>;
export type UserSessionCursor = z.infer<typeof sessionCursorSchema>;
export type ListUserSessionsInput = z.input<typeof listSessionsInputSchema>;

export interface UserSessionSummary {
  conversationId: string;
  title: string;
  latestMessagePreview: string;
  lastRunId: string;
  runCount: number;
  createdAt: number;
  updatedAt: number;
}

export interface UserSessionPage {
  sessions: UserSessionSummary[];
  nextCursor: UserSessionCursor | null;
}

export interface ProjectSourceItem {
  id: string;
  source_id: string;
  provider: 'youtube';
  entity_type: 'search' | 'video' | 'playlist' | 'channel';
  entity_id: string;
  title: string;
  created_at: number;
}

interface ProjectSourceRow extends Record<string, SqlStorageValue> {
  id: string;
  source_id: string;
  input: string;
  title: string;
  kind: RecentSource['kind'];
  snapshot: string;
  created_at: number;
}

interface PinRow extends Record<string, SqlStorageValue> {
  source_id: string | null;
  source_revision: string | null;
  input: string;
  title: string;
  kind: RecentSource['kind'];
  snapshot: string;
  created_at: number;
}

/** The owned D1 item a pin may describe. */
export interface PinIdentity { provider: string; type: string; id: string }

export type PinResult = { ok: true; itemId: string; sourceId: string | null; sourceRevision: string }
  | { ok: false; code: 'SOURCE_NOT_FOUND' | 'SOURCE_REVISION_MISMATCH' | 'SOURCE_IDENTITY_MISMATCH' };

export interface StoredSourceReference {
  origin: 'project-source' | 'pin' | 'recent';
  source: RecentSource;
  snapshot: SourceReference;
  sourceRevision: string;
}

function matchesIdentity(snapshot: SourceReference, expected: PinIdentity): boolean {
  return snapshot.kind === 'inspection' && snapshot.inspector.provider === expected.provider
    && snapshot.inspector.type === expected.type && snapshot.inspector.id === expected.id;
}

interface SessionRow extends Record<string, SqlStorageValue> {
  conversation_id: string;
  title: string;
  search_text: string;
  latest_message_preview: string;
  last_run_id: string;
  run_count: number;
  created_at: number;
  updated_at: number;
}

interface SessionRunRow extends Record<string, SqlStorageValue> {
  run_id: string;
  conversation_id: string;
}

export class UserAccountDO extends DurableObject<Env> {
  readonly #admissions: AgentAdmissionQueue;
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.#admissions = new AgentAdmissionQueue(ctx, env, { assertActive: () => this.assertActive(),
      register: id => this.registerConversation(id), record: input => this.recordSession(input) });
    ctx.blockConcurrencyWhile(async () => {
      this.ensureSchema();
      this.#admissions.initialize();
    });
  }

  enqueueAgentRun(request: AgentRequest, admission: AgentAdmission) { return this.#admissions.enqueue(request, admission); }
  async pendingAgentRun(conversationId: string, runId?: string) {
    this.assertActive();
    return this.#admissions.pending(conversationId, runId);
  }
  async alarm(): Promise<void> { await this.#admissions.alarm(); }

  registerConversation(conversationId: string): void {
    this.assertActive();
    if (this.#admissions.pending(conversationId)) throw new Error('Conversation admission is pending.');
    this.ctx.storage.sql.exec('INSERT OR IGNORE INTO agent_conversations (conversation_id) VALUES (?)',
      z.string().uuid().parse(conversationId));
  }

  /**
   * Follow-ups may only name a session this account already has. New session
   * IDs are always generated by the server, so callers cannot reuse another
   * account's ID. Returns false for an unknown session.
   */
  continueConversation(conversationId: string): boolean {
    this.assertActive();
    const id = z.string().uuid().parse(conversationId);
    if (this.#admissions.pending(id)) throw new Error('Conversation admission is pending.');
    const known = this.ctx.storage.sql.exec(
      'SELECT 1 FROM agent_conversations WHERE conversation_id = ? UNION SELECT 1 FROM user_sessions WHERE conversation_id = ? LIMIT 1',
      id, id,
    ).toArray().length > 0;
    // Older sessions may predate agent_conversations; register them on use.
    if (known) this.ctx.storage.sql.exec('INSERT OR IGNORE INTO agent_conversations (conversation_id) VALUES (?)', id);
    return known;
  }

  beginDeletion(): string[] {
    this.ctx.storage.sql.exec('INSERT OR IGNORE INTO account_deletion (id) VALUES (1)');
    return this.ctx.storage.sql.exec<{ conversation_id: string }>(
      'SELECT conversation_id FROM agent_conversations UNION SELECT conversation_id FROM user_sessions',
    ).toArray().map(row => row.conversation_id);
  }

  finishDeletion(): void {
    this.#admissions.clear();
    this.ctx.storage.sql.exec('DELETE FROM user_sessions_fts');
    this.ctx.storage.sql.exec('DELETE FROM user_session_runs');
    this.ctx.storage.sql.exec('DELETE FROM user_sessions');
    this.ctx.storage.sql.exec('DELETE FROM agent_conversations');
    this.ctx.storage.sql.exec('DELETE FROM recent_sources');
    this.ctx.storage.sql.exec('DELETE FROM project_sources');
    this.ctx.storage.sql.exec('DELETE FROM project_item_snapshots');
    // Keep only a tombstone so already-authenticated requests cannot recreate data.
  }

  private assertActive(): void {
    if (this.ctx.storage.sql.exec('SELECT id FROM account_deletion LIMIT 1').toArray().length) {
      throw new Error('Account deletion is in progress.');
    }
  }

  saveSource(value: SaveReferencedSource): RecentSource {
    this.assertActive();
    const input = saveReferencedSourceSchema.parse(value);
    const snapshot = JSON.stringify(input.snapshot);
    const key = sourceIdentity(input);
    const existing = this.ctx.storage.sql.exec<{ id: string }>('SELECT id FROM recent_sources WHERE source_key = ?', key).toArray()[0];
    const entry: RecentSource = { id: existing?.id ?? crypto.randomUUID(), input: input.input,
      title: input.title,
      kind: input.snapshot.kind, updatedAt: this.nextSourceUpdate(),
      ...(input.snapshot.kind === 'inspection' && input.snapshot.inspector.thumbnailUrl ? { thumbnailUrl: input.snapshot.inspector.thumbnailUrl } : {}) };
    this.ctx.storage.transactionSync(() => {
      this.ctx.storage.sql.exec(`INSERT INTO recent_sources (id, source_key, input, title, kind, updated_at, snapshot)
        VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(source_key) DO UPDATE SET
        input=excluded.input, title=excluded.title, kind=excluded.kind, updated_at=excluded.updated_at, snapshot=excluded.snapshot`,
        entry.id, key, entry.input, entry.title, entry.kind, entry.updatedAt, snapshot);
      this.ctx.storage.sql.exec(`DELETE FROM recent_sources WHERE id NOT IN
        (SELECT id FROM recent_sources ORDER BY updated_at DESC, rowid DESC LIMIT ?)`, RECENT_SOURCE_LIMIT);
    });
    return entry;
  }

  /** Compare the old references and retain an appended page and its optional project link atomically. */
  async replaceSourceReferences(id: string, expected: SourceReference, value: SaveReferencedSource,
    destination?: { projectId: string; itemId?: string }) {
    this.assertActive();
    const sourceId = sourceIdSchema.parse(id), input = saveReferencedSourceSchema.parse(value);
    const project = destination ? z.string().uuid().parse(destination.projectId) : undefined;
    const item = destination?.itemId ? sourceIdSchema.parse(destination.itemId) : undefined;
    const expectedPayload = sourceRevisionPayload(expected);
    const revision = await sourceRevision(input.snapshot);
    this.assertActive();
    return this.ctx.storage.transactionSync(() => {
      const row = this.ctx.storage.sql.exec<{ source_key: string; snapshot: string }>(
        'SELECT source_key, snapshot FROM recent_sources WHERE id = ?', sourceId).toArray()[0];
      if (!row || row.source_key !== sourceIdentity(input) || sourceRevisionPayload(sourceReferenceSchema.parse(JSON.parse(row.snapshot))) !== expectedPayload) {
        return { ok: false as const };
      }
      const source = this.saveSource(input);
      if (project && item) this.writePin(project, item, source.id, revision, input);
      const linked = project && !item ? this.linkSourceToProject(project, source.id) : null;
      return { ok: true as const, source, sourceRevision: revision, linked };
    });
  }

  listSources(): RecentSource[] {
    this.assertActive();
    return this.ctx.storage.sql.exec<{ id: string; input: string; title: string; kind: RecentSource['kind']; updated_at: number; thumbnail_url: string | null }>(
      `SELECT id, input, title, kind, updated_at, json_extract(snapshot, '$.inspector.thumbnailUrl') AS thumbnail_url
       FROM recent_sources ORDER BY updated_at DESC, rowid DESC LIMIT ?`, RECENT_SOURCE_LIMIT,
    ).toArray().map(({ updated_at, thumbnail_url, ...row }) => ({ ...row, updatedAt: updated_at, ...(thumbnail_url ? { thumbnailUrl: thumbnail_url } : {}) }));
  }

  listSourceReferences() {
    return this.listSources().map(source => ({ source, snapshot: source.kind === 'inspection' && !source.thumbnailUrl
      ? sourceReferenceSchema.parse(JSON.parse(this.ctx.storage.sql.exec<{ snapshot: string }>('SELECT snapshot FROM recent_sources WHERE id = ?', source.id).one().snapshot)) : null }));
  }

  cacheSourceThumbnail(id: string, url: string): void {
    this.assertActive();
    this.ctx.storage.sql.exec(`UPDATE recent_sources SET snapshot = json_set(snapshot, '$.inspector.thumbnailUrl', ?)
      WHERE id = ? AND kind = 'inspection' AND json_extract(snapshot, '$.inspector.thumbnailUrl') IS NULL`, z.string().url().parse(url), z.string().uuid().parse(id));
  }

  getSource(id: string): { source: RecentSource; snapshot: SourceReference } | null {
    this.assertActive();
    const sourceId = sourceIdSchema.parse(id);
    const row = this.ctx.storage.sql.exec<{ id: string; input: string; title: string; kind: RecentSource['kind']; updated_at: number; snapshot: string }>(
      'SELECT id, input, title, kind, updated_at, snapshot FROM recent_sources WHERE id = ?', sourceId,
    ).toArray()[0];
    if (row) {
      const updatedAt = this.nextSourceUpdate();
      this.ctx.storage.sql.exec('UPDATE recent_sources SET updated_at = ? WHERE id = ?', updatedAt, id);
      return { source: { id: row.id, input: row.input, title: row.title, kind: row.kind, updatedAt },
        snapshot: sourceReferenceSchema.parse(JSON.parse(row.snapshot)) };
    }
    return null;
  }

  saveSourceWithProject(value: SaveReferencedSource, projectId?: string) {
    this.assertActive();
    const project = projectId === undefined ? undefined : z.string().uuid().parse(projectId);
    return this.ctx.storage.transactionSync(() => {
      const source = this.saveSource(value);
      const linked = project ? this.linkSourceToProject(project, source.id) : null;
      if (project && !linked) throw new Error('Saved source could not be linked.');
      return { source, linked };
    });
  }

  getProjectSource(projectId: string, itemId: string): { item: ProjectSourceItem; source: RecentSource; snapshot: SourceReference } | null {
    this.assertActive();
    const saved = this.ctx.storage.sql.exec<ProjectSourceRow>(
      'SELECT id, source_id, input, title, kind, snapshot, created_at FROM project_sources WHERE project_id = ? AND id = ?',
      z.string().uuid().parse(projectId), sourceIdSchema.parse(itemId),
    ).toArray()[0];
    if (!saved) return null;
    return { item: this.toProjectSourceItem(saved), source: { id: saved.source_id, input: saved.input, title: saved.title, kind: saved.kind, updatedAt: saved.created_at },
      snapshot: sourceReferenceSchema.parse(JSON.parse(saved.snapshot)) };
  }

  /**
   * Explicit Save only. The sidecar is keyed by an existing D1 item and is
   * never listed as another project row. A later explicit Save replaces it.
   */
  async pinProjectItem(projectId: string, itemId: string, value: SaveReferencedSource, expected: PinIdentity, condition?: SourceCondition): Promise<PinResult> {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), item = sourceIdSchema.parse(itemId);
    const input = saveReferencedSourceSchema.parse(value);
    if (!matchesIdentity(input.snapshot, expected)) return { ok: false, code: 'SOURCE_IDENTITY_MISMATCH' };
    const revision = await sourceRevision(input.snapshot);
    this.assertActive();
    return this.ctx.storage.transactionSync((): PinResult => {
      if (condition && !this.matchesSourceCondition(condition)) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
      this.writePin(project, item, null, revision, input);
      return { ok: true, itemId: item, sourceId: null, sourceRevision: revision };
    });
  }

  /** Copy the exact Recent version that the browser displayed, or reject a newer replacement. */
  async pinProjectItemFromRecent(projectId: string, itemId: string, sourceId: string, expectedRevision: string, expected: PinIdentity): Promise<PinResult> {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), item = sourceIdSchema.parse(itemId);
    const source = sourceIdSchema.parse(sourceId), revision = sourceRevisionSchema.parse(expectedRevision);
    const read = () => this.ctx.storage.sql.exec<{ input: string; title: string; snapshot: string }>(
      'SELECT input, title, snapshot FROM recent_sources WHERE id = ?', source,
    ).toArray()[0];
    const recent = read();
    if (!recent) return { ok: false, code: 'SOURCE_NOT_FOUND' };
    const snapshot = sourceReferenceSchema.parse(JSON.parse(recent.snapshot));
    if (await sourceRevision(snapshot) !== revision) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
    if (!matchesIdentity(snapshot, expected)) return { ok: false, code: 'SOURCE_IDENTITY_MISMATCH' };
    const payload = sourceRevisionPayload(snapshot);
    this.assertActive();
    // Hashing yields to other requests, so confirm the row still has the hashed references.
    // A thumbnail cached in the meantime is cosmetic and does not make it a newer version.
    return this.ctx.storage.transactionSync((): PinResult => {
      const current = read();
      const currentSnapshot = current ? sourceReferenceSchema.parse(JSON.parse(current.snapshot)) : null;
      if (!current || !currentSnapshot || sourceRevisionPayload(currentSnapshot) !== payload) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
      this.writePin(project, item, source, revision, { input: current.input, title: current.title, snapshot: currentSnapshot });
      return { ok: true, itemId: item, sourceId: source, sourceRevision: revision };
    });
  }

  /**
   * Add sources mode when the project already holds this whole source as a D1 item:
   * save Recent and retain the reference alongside that item in one transaction,
   * instead of adding a project source row.
   */
  async saveSourceWithItemPin(value: SaveReferencedSource, projectId: string, itemId: string, expected: PinIdentity) {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), item = sourceIdSchema.parse(itemId);
    const input = saveReferencedSourceSchema.parse(value);
    if (!matchesIdentity(input.snapshot, expected)) throw new Error('Saved source does not match the project item.');
    const revision = await sourceRevision(input.snapshot);
    this.assertActive();
    return this.ctx.storage.transactionSync(() => {
      const source = this.saveSource(input);
      this.writePin(project, item, source.id, revision, input);
      return { source, sourceRevision: revision };
    });
  }

  /** Identity of a Recent entry without reordering Recent. */
  peekSourceKey(sourceId: string): string | null {
    this.assertActive();
    return this.ctx.storage.sql.exec<{ source_key: string }>('SELECT source_key FROM recent_sources WHERE id = ?', sourceIdSchema.parse(sourceId)).toArray()[0]?.source_key ?? null;
  }

  /** D1 items in a project that retain this Recent entry, newest first; moments and whole sources alike. */
  pinnedItemsForSource(projectId: string, sourceId: string): string[] {
    this.assertActive();
    return this.ctx.storage.sql.exec<{ item_id: string }>('SELECT item_id FROM project_item_snapshots WHERE project_id = ? AND source_id = ? ORDER BY created_at DESC LIMIT 50',
      z.string().uuid().parse(projectId), sourceIdSchema.parse(sourceId)).toArray().map(row => row.item_id);
  }

  /** Link a Recent entry to an existing D1 whole-source item, copying its current references as linkSourceToProject does. */
  async linkSourceToItem(projectId: string, sourceId: string, itemId: string, expected: PinIdentity): Promise<PinResult> {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), item = sourceIdSchema.parse(itemId), source = sourceIdSchema.parse(sourceId);
    const read = () => this.ctx.storage.sql.exec<{ input: string; title: string; snapshot: string }>('SELECT input, title, snapshot FROM recent_sources WHERE id = ?', source).toArray()[0];
    const recent = read();
    if (!recent) return { ok: false, code: 'SOURCE_NOT_FOUND' };
    const snapshot = sourceReferenceSchema.parse(JSON.parse(recent.snapshot));
    if (!matchesIdentity(snapshot, expected)) return { ok: false, code: 'SOURCE_IDENTITY_MISMATCH' };
    const revision = await sourceRevision(snapshot), payload = sourceRevisionPayload(snapshot);
    this.assertActive();
    return this.ctx.storage.transactionSync((): PinResult => {
      const current = read();
      const currentSnapshot = current ? sourceReferenceSchema.parse(JSON.parse(current.snapshot)) : null;
      if (!current || !currentSnapshot || sourceRevisionPayload(currentSnapshot) !== payload) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
      this.writePin(project, item, source, revision, { input: current.input, title: current.title, snapshot: currentSnapshot });
      return { ok: true, itemId: item, sourceId: source, sourceRevision: revision };
    });
  }

  /** The existing project source row for one whole source, so a standalone Save reuses it instead of adding a D1 row. */
  findProjectSourceItem(projectId: string, sourceKey: string): string | null {
    this.assertActive();
    return this.ctx.storage.sql.exec<{ id: string }>(
      'SELECT id FROM project_sources WHERE project_id = ? AND source_key = ?',
      z.string().uuid().parse(projectId), z.string().min(1).max(500).parse(sourceKey),
    ).toArray()[0]?.id ?? null;
  }

  /**
   * Explicit Save onto an existing project source row: replace its references
   * with the exact Recent revision, or with a stored descriptor, keeping its ID.
   */
  async refreshProjectSource(projectId: string, itemId: string, value: SaveReferencedSource | { sourceId: string; sourceRevision: string }, expected: PinIdentity, condition?: SourceCondition): Promise<PinResult> {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), item = sourceIdSchema.parse(itemId);
    const readRow = () => this.ctx.storage.sql.exec<{ source_key: string }>('SELECT source_key FROM project_sources WHERE project_id = ? AND id = ?', project, item).toArray()[0];
    const row = readRow();
    if (!row) return { ok: false, code: 'SOURCE_NOT_FOUND' };
    let input: SaveReferencedSource, sourceId: string, recentText: string | null = null;
    if ('sourceRevision' in value) {
      sourceId = sourceIdSchema.parse(value.sourceId);
      const recent = this.ctx.storage.sql.exec<{ input: string; title: string; snapshot: string }>('SELECT input, title, snapshot FROM recent_sources WHERE id = ?', sourceId).toArray()[0];
      if (!recent) return { ok: false, code: 'SOURCE_NOT_FOUND' };
      const snapshot = sourceReferenceSchema.parse(JSON.parse(recent.snapshot));
      if (await sourceRevision(snapshot) !== sourceRevisionSchema.parse(value.sourceRevision)) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
      input = { input: recent.input, title: recent.title, snapshot }; recentText = sourceRevisionPayload(snapshot);
    } else { input = saveReferencedSourceSchema.parse(value); sourceId = ''; }
    if (!matchesIdentity(input.snapshot, expected) || sourceIdentity(input) !== row.source_key) return { ok: false, code: 'SOURCE_IDENTITY_MISMATCH' };
    const revision = await sourceRevision(input.snapshot);
    this.assertActive();
    return this.ctx.storage.transactionSync((): PinResult => {
      if (!readRow()) return { ok: false, code: 'SOURCE_NOT_FOUND' };
      if (condition && !this.matchesSourceCondition(condition)) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
      if (recentText !== null) {
        // Compare references, not text: a thumbnail cached meanwhile is not a newer version.
        const current = this.ctx.storage.sql.exec<{ snapshot: string }>('SELECT snapshot FROM recent_sources WHERE id = ?', sourceId).toArray()[0];
        const currentSnapshot = current ? sourceReferenceSchema.parse(JSON.parse(current.snapshot)) : null;
        if (!currentSnapshot || sourceRevisionPayload(currentSnapshot) !== recentText) return { ok: false, code: 'SOURCE_REVISION_MISMATCH' };
        input = { ...input, snapshot: currentSnapshot };
      }
      this.ctx.storage.sql.exec(`UPDATE project_sources SET ${sourceId ? 'source_id = ?, ' : ''}input = ?, title = ?, snapshot = ? WHERE project_id = ? AND id = ?`,
        ...(sourceId ? [sourceId] : []), input.input, input.title, JSON.stringify(sourceReferenceSchema.parse(input.snapshot)), project, item);
      return { ok: true, itemId: item, sourceId: sourceId || null, sourceRevision: revision };
    });
  }

  getProjectItemPin(projectId: string, itemId: string): StoredSourceReference | null {
    this.assertActive();
    const row = this.ctx.storage.sql.exec<PinRow>(
      `SELECT source_id, source_revision, input, title, kind, snapshot, created_at
       FROM project_item_snapshots WHERE project_id = ? AND item_id = ?`,
      z.string().uuid().parse(projectId), sourceIdSchema.parse(itemId),
    ).toArray()[0];
    return row ? this.toStoredReference(row, 'pin', row.source_id ?? itemId) : null;
  }

  /**
   * Read-only owned references for one source in one project, then Recent.
   * Opening a project never reorders Recent or writes a reference.
   */
  async ownedSourceReferences(projectId: string, sourceKey: string): Promise<StoredSourceReference[]> {
    this.assertActive();
    const project = z.string().uuid().parse(projectId), key = z.string().min(1).max(500).parse(sourceKey);
    const projectRows = this.ctx.storage.sql.exec<ProjectSourceRow>(
      'SELECT id, source_id, input, title, kind, snapshot, created_at FROM project_sources WHERE project_id = ? AND source_key = ? ORDER BY created_at DESC',
      project, key,
    ).toArray();
    const pins = this.ctx.storage.sql.exec<PinRow & { item_id: string }>(
      `SELECT item_id, source_id, source_revision, input, title, kind, snapshot, created_at
       FROM project_item_snapshots WHERE project_id = ? AND source_key = ? ORDER BY created_at DESC`, project, key,
    ).toArray();
    const recent = this.ctx.storage.sql.exec<{ id: string; input: string; title: string; kind: RecentSource['kind']; updated_at: number; snapshot: string }>(
      'SELECT id, input, title, kind, updated_at, snapshot FROM recent_sources WHERE source_key = ?', key,
    ).toArray()[0];
    const references = [
      ...projectRows.map(row => ({ origin: 'project-source' as const, row: { ...row, source_revision: null }, sourceId: row.source_id })),
      ...pins.map(row => ({ origin: 'pin' as const, row, sourceId: row.source_id ?? row.item_id })),
      ...(recent ? [{ origin: 'recent' as const, row: { ...recent, source_id: recent.id, source_revision: null, created_at: recent.updated_at }, sourceId: recent.id }] : []),
    ];
    return Promise.all(references.map(async ({ origin, row, sourceId }) => {
      const reference = this.toStoredReference(row, origin, sourceId);
      return row.source_revision ? reference : { ...reference, sourceRevision: await sourceRevision(reference.snapshot) };
    }));
  }

  /** Call only inside the transaction that writes the dependent references. */
  private matchesSourceCondition(condition: SourceCondition): boolean {
    const row = this.ctx.storage.sql.exec<{ snapshot: string }>('SELECT snapshot FROM recent_sources WHERE id = ?',
      sourceIdSchema.parse(condition.sourceId)).toArray()[0];
    return Boolean(row && sourceRevisionPayload(sourceReferenceSchema.parse(JSON.parse(row.snapshot))) === sourceRevisionPayload(condition.snapshot));
  }

  private writePin(project: string, item: string, sourceId: string | null, revision: string, input: SaveReferencedSource): void {
    this.ctx.storage.sql.exec(`INSERT INTO project_item_snapshots
      (project_id, item_id, source_id, source_revision, source_key, input, title, kind, snapshot, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(project_id, item_id) DO UPDATE SET source_id=excluded.source_id, source_revision=excluded.source_revision,
        source_key=excluded.source_key, input=excluded.input, title=excluded.title,
        kind=excluded.kind, snapshot=excluded.snapshot, created_at=excluded.created_at`,
      project, item, sourceId, revision, sourceIdentity(input), input.input, input.title, input.snapshot.kind,
      JSON.stringify(sourceReferenceSchema.parse(input.snapshot)), Date.now());
  }

  private toStoredReference(row: { source_id: string | null; source_revision: string | null; input: string; title: string; kind: RecentSource['kind']; snapshot: string; created_at: number }, origin: StoredSourceReference['origin'], sourceId: string): StoredSourceReference {
    const snapshot = sourceReferenceSchema.parse(JSON.parse(row.snapshot));
    return { origin, source: { id: sourceId, input: row.input, title: row.title, kind: row.kind, updatedAt: row.created_at },
      snapshot, sourceRevision: row.source_revision ?? '' };
  }

  linkSourceToProject(projectId: string, sourceId: string): { item: ProjectSourceItem; added: boolean } | null {
    this.assertActive();
    const project = z.string().uuid().parse(projectId);
    const source = sourceIdSchema.parse(sourceId);
    const recent = this.ctx.storage.sql.exec<{ source_key: string; input: string; title: string; kind: RecentSource['kind']; snapshot: string }>(
      'SELECT source_key, input, title, kind, snapshot FROM recent_sources WHERE id = ?', source,
    ).toArray()[0];
    if (!recent) {
      const saved = this.ctx.storage.sql.exec<ProjectSourceRow>(
        'SELECT id, source_id, input, title, kind, snapshot, created_at FROM project_sources WHERE project_id = ? AND source_id = ?', project, source,
      ).toArray()[0];
      return saved ? { item: this.toProjectSourceItem(saved), added: false } : null;
    }
    const existing = this.ctx.storage.sql.exec<{ id: string }>(
      'SELECT id FROM project_sources WHERE project_id = ? AND source_key = ?', project, recent.source_key,
    ).toArray()[0];
    const id = existing?.id ?? crypto.randomUUID();
    const createdAt = Date.now();
    this.ctx.storage.sql.exec(`INSERT INTO project_sources
      (id, project_id, source_key, source_id, input, title, kind, snapshot, created_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(project_id, source_key) DO UPDATE SET
        source_id=excluded.source_id, input=excluded.input, title=excluded.title,
        kind=excluded.kind, snapshot=excluded.snapshot`,
      id, project, recent.source_key, source, recent.input, recent.title, recent.kind, recent.snapshot, createdAt);
    const saved = this.ctx.storage.sql.exec<ProjectSourceRow>(
      'SELECT id, source_id, input, title, kind, snapshot, created_at FROM project_sources WHERE id = ?', id,
    ).one();
    return { item: this.toProjectSourceItem(saved), added: !existing };
  }

  listProjectSources(projectId: string): ProjectSourceItem[] {
    this.assertActive();
    const rows = this.ctx.storage.sql.exec<ProjectSourceRow>(
      'SELECT id, source_id, input, title, kind, snapshot, created_at FROM project_sources WHERE project_id = ? ORDER BY created_at DESC',
      z.string().uuid().parse(projectId),
    ).toArray();
    return rows.map(row => this.toProjectSourceItem(row));
  }

  projectSourceCounts(): Array<{ projectId: string; count: number }> {
    this.assertActive();
    return this.ctx.storage.sql.exec<{ project_id: string; count: number }>(
      'SELECT project_id, COUNT(*) AS count FROM project_sources GROUP BY project_id',
    ).toArray().map(row => ({ projectId: row.project_id, count: row.count }));
  }

  removeProjectSources(projectId: string): void {
    this.assertActive();
    const project = z.string().uuid().parse(projectId);
    this.ctx.storage.transactionSync(() => {
      this.ctx.storage.sql.exec('DELETE FROM project_sources WHERE project_id = ?', project);
      this.ctx.storage.sql.exec('DELETE FROM project_item_snapshots WHERE project_id = ?', project);
    });
  }

  private toProjectSourceItem(row: ProjectSourceRow): ProjectSourceItem {
    const snapshot = sourceReferenceSchema.parse(JSON.parse(row.snapshot));
    return { id: row.id, source_id: row.source_id, provider: 'youtube',
      entity_type: snapshot.kind === 'search' ? 'search' : snapshot.inspector.type,
      entity_id: snapshot.kind === 'search' ? row.source_id : snapshot.inspector.id,
      title: row.title, created_at: row.created_at };
  }

  private nextSourceUpdate(): number {
    const latest = this.ctx.storage.sql.exec<{ latest: number | null }>('SELECT MAX(updated_at) AS latest FROM recent_sources').one().latest;
    return Math.max(Date.now(), (latest ?? 0) + 1);
  }

  recordSession(value: RecordSessionInput): UserSessionSummary {
    this.assertActive();
    const input = recordSessionInputSchema.parse(value);
    const existingRun = this.ctx.storage.sql.exec<SessionRunRow>(
      'SELECT run_id, conversation_id FROM user_session_runs WHERE run_id = ? LIMIT 1',
      input.runId,
    ).toArray()[0];
    if (existingRun && existingRun.conversation_id !== input.conversationId) {
      throw new Error('A run cannot belong to more than one user session.');
    }

    const existing = this.readSession(input.conversationId);
    const title = existing?.title ?? titleFromMessage(input.message);
    const isNewRun = !existingRun;
    const advancesLatest = !existing || input.updatedAt >= existing.updated_at;
    const searchText = isNewRun
      ? appendSearchText(existing?.search_text ?? '', input.message)
      : existing?.search_text ?? input.message;
    const latestMessagePreview = advancesLatest
      ? previewFromMessage(input.message)
      : existing!.latest_message_preview;
    const lastRunId = advancesLatest ? input.runId : existing!.last_run_id;
    const createdAt = existing?.created_at ?? input.updatedAt;
    const updatedAt = advancesLatest ? input.updatedAt : existing!.updated_at;
    const runCount = (existing?.run_count ?? 0) + (isNewRun ? 1 : 0);

    if (isNewRun) {
      this.ctx.storage.sql.exec(
        'INSERT INTO user_session_runs (run_id, conversation_id, created_at) VALUES (?, ?, ?)',
        input.runId,
        input.conversationId,
        input.updatedAt,
      );
    }
    this.ctx.storage.sql.exec(
      `INSERT INTO user_sessions (
        conversation_id, title, search_text, latest_message_preview,
        last_run_id, run_count, created_at, updated_at
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(conversation_id) DO UPDATE SET
        title = excluded.title,
        search_text = excluded.search_text,
        latest_message_preview = excluded.latest_message_preview,
        last_run_id = excluded.last_run_id,
        run_count = excluded.run_count,
        updated_at = excluded.updated_at`,
      input.conversationId,
      title,
      searchText,
      latestMessagePreview,
      lastRunId,
      runCount,
      createdAt,
      updatedAt,
    );
    this.ctx.storage.sql.exec(
      'DELETE FROM user_sessions_fts WHERE conversation_id = ?',
      input.conversationId,
    );
    this.ctx.storage.sql.exec(
      'INSERT INTO user_sessions_fts (conversation_id, title, search_text) VALUES (?, ?, ?)',
      input.conversationId,
      title,
      searchText,
    );

    return {
      conversationId: input.conversationId,
      title,
      latestMessagePreview,
      lastRunId,
      runCount,
      createdAt,
      updatedAt,
    };
  }

  listSessions(value: ListUserSessionsInput = {}): UserSessionPage {
    const input = listSessionsInputSchema.parse(value);
    const fetchLimit = input.limit + 1;
    const ftsQuery = input.query ? buildFtsQuery(input.query) : '';
    if (input.query && !ftsQuery) return { sessions: [], nextCursor: null };

    const rows = ftsQuery
      ? this.searchRows(ftsQuery, input.cursor, fetchLimit)
      : this.listRows(input.cursor, fetchLimit);
    const hasMore = rows.length > input.limit;
    const pageRows = hasMore ? rows.slice(0, input.limit) : rows;
    const last = pageRows.at(-1);
    return {
      sessions: pageRows.map(toSessionSummary),
      nextCursor: hasMore && last
        ? { updatedAt: last.updated_at, conversationId: last.conversation_id }
        : null,
    };
  }

  /** Stable pagination for operator migrations, unaffected by session activity. */
  listSessionAssetMigrationTargets(after?: string) {
    if (after !== undefined) z.string().uuid().parse(after);
    const rows = this.ctx.storage.sql.exec<{ conversation_id: string }>(
      'SELECT conversation_id FROM user_sessions WHERE conversation_id>? ORDER BY conversation_id LIMIT 101',
      after ?? '',
    ).toArray();
    return {
      conversationIds: rows.slice(0, 100).map(row => row.conversation_id),
      nextCursor: rows.length > 100 ? rows[99]!.conversation_id : null,
    };
  }

  getSession(conversationId: string): UserSessionSummary | null {
    const parsedConversationId = z.string().uuid().parse(conversationId);
    const row = this.readSession(parsedConversationId);
    return row ? toSessionSummary(row) : null;
  }

  private listRows(cursor: UserSessionCursor | undefined, limit: number): SessionRow[] {
    if (!cursor) {
      return this.ctx.storage.sql.exec<SessionRow>(
        `SELECT * FROM user_sessions
        ORDER BY updated_at DESC, conversation_id DESC
        LIMIT ?`,
        limit,
      ).toArray();
    }
    return this.ctx.storage.sql.exec<SessionRow>(
      `SELECT * FROM user_sessions
      WHERE updated_at < ? OR (updated_at = ? AND conversation_id < ?)
      ORDER BY updated_at DESC, conversation_id DESC
      LIMIT ?`,
      cursor.updatedAt,
      cursor.updatedAt,
      cursor.conversationId,
      limit,
    ).toArray();
  }

  private searchRows(query: string, cursor: UserSessionCursor | undefined, limit: number): SessionRow[] {
    if (!cursor) {
      return this.ctx.storage.sql.exec<SessionRow>(
        `SELECT sessions.*
        FROM user_sessions_fts
        JOIN user_sessions AS sessions USING (conversation_id)
        WHERE user_sessions_fts MATCH ?
        ORDER BY sessions.updated_at DESC, sessions.conversation_id DESC
        LIMIT ?`,
        query,
        limit,
      ).toArray();
    }
    return this.ctx.storage.sql.exec<SessionRow>(
      `SELECT sessions.*
      FROM user_sessions_fts
      JOIN user_sessions AS sessions USING (conversation_id)
      WHERE user_sessions_fts MATCH ?
        AND (sessions.updated_at < ? OR (sessions.updated_at = ? AND sessions.conversation_id < ?))
      ORDER BY sessions.updated_at DESC, sessions.conversation_id DESC
      LIMIT ?`,
      query,
      cursor.updatedAt,
      cursor.updatedAt,
      cursor.conversationId,
      limit,
    ).toArray();
  }

  private readSession(conversationId: string): SessionRow | undefined {
    return this.ctx.storage.sql.exec<SessionRow>(
      'SELECT * FROM user_sessions WHERE conversation_id = ? LIMIT 1',
      conversationId,
    ).toArray()[0];
  }

  private ensureSchema(): void {
    this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS recent_sources (
      id TEXT PRIMARY KEY, source_key TEXT NOT NULL UNIQUE, input TEXT NOT NULL, title TEXT NOT NULL,
      kind TEXT NOT NULL, updated_at INTEGER NOT NULL, snapshot TEXT NOT NULL
    )`);
    this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS project_sources (
      id TEXT PRIMARY KEY, project_id TEXT NOT NULL, source_key TEXT NOT NULL,
      source_id TEXT NOT NULL, input TEXT NOT NULL, title TEXT NOT NULL,
      kind TEXT NOT NULL, snapshot TEXT NOT NULL, created_at INTEGER NOT NULL,
      UNIQUE(project_id, source_key)
    )`);
    this.ctx.storage.sql.exec(`CREATE TABLE IF NOT EXISTS project_item_snapshots (
      project_id TEXT NOT NULL, item_id TEXT NOT NULL, source_id TEXT, source_revision TEXT NOT NULL, source_key TEXT NOT NULL,
      input TEXT NOT NULL, title TEXT NOT NULL, kind TEXT NOT NULL, snapshot TEXT NOT NULL, created_at INTEGER NOT NULL,
      PRIMARY KEY(project_id, item_id)
    )`);
    this.ctx.storage.sql.exec('CREATE INDEX IF NOT EXISTS project_item_snapshots_source_idx ON project_item_snapshots (project_id, source_key)');
    this.ctx.storage.sql.exec('CREATE INDEX IF NOT EXISTS project_sources_project_idx ON project_sources (project_id, created_at DESC)');
    this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS account_deletion (id INTEGER PRIMARY KEY)');
    this.ctx.storage.sql.exec('CREATE TABLE IF NOT EXISTS agent_conversations (conversation_id TEXT PRIMARY KEY)');
    this.ctx.storage.sql.exec(`
      CREATE TABLE IF NOT EXISTS _sql_schema_migrations (
        id INTEGER PRIMARY KEY,
        applied_at INTEGER NOT NULL
      )
    `);
    this.ctx.storage.sql.exec(`
      CREATE TABLE IF NOT EXISTS user_sessions (
        conversation_id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        search_text TEXT NOT NULL,
        latest_message_preview TEXT NOT NULL,
        last_run_id TEXT NOT NULL,
        run_count INTEGER NOT NULL,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL
      )
    `);
    this.ctx.storage.sql.exec(`
      CREATE INDEX IF NOT EXISTS user_sessions_updated_idx
      ON user_sessions (updated_at DESC, conversation_id DESC)
    `);
    this.ctx.storage.sql.exec(`
      CREATE TABLE IF NOT EXISTS user_session_runs (
        run_id TEXT PRIMARY KEY,
        conversation_id TEXT NOT NULL,
        created_at INTEGER NOT NULL
      )
    `);
    this.ctx.storage.sql.exec(`
      CREATE INDEX IF NOT EXISTS user_session_runs_conversation_idx
      ON user_session_runs (conversation_id, created_at)
    `);
    this.ctx.storage.sql.exec(`
      CREATE VIRTUAL TABLE IF NOT EXISTS user_sessions_fts
      USING fts5(conversation_id UNINDEXED, title, search_text, tokenize = 'unicode61')
    `);
    this.ctx.storage.sql.exec(
      'INSERT OR IGNORE INTO _sql_schema_migrations (id, applied_at) VALUES (1, ?)',
      Date.now(),
    );
  }
}

export function titleFromMessage(message: string): string {
  const normalized = normalizeText(message);
  if (normalized.length <= MAX_TITLE_LENGTH) return normalized;
  return `${normalized.slice(0, MAX_TITLE_LENGTH - 3)}...`;
}

export function previewFromMessage(message: string): string {
  const normalized = normalizeText(message);
  if (normalized.length <= MAX_PREVIEW_LENGTH) return normalized;
  return `${normalized.slice(0, MAX_PREVIEW_LENGTH - 3)}...`;
}

export function buildFtsQuery(query: string): string {
  const tokens = normalizeText(query)
    .match(/[\p{L}\p{N}_]+/gu)
    ?.slice(0, MAX_SEARCH_TOKENS) ?? [];
  return tokens.map((token) => `"${token.replaceAll('"', '""')}"*`).join(' AND ');
}

export function encodeSessionCursor(cursor: UserSessionCursor): string {
  const parsed = sessionCursorSchema.parse(cursor);
  return base64UrlEncode(JSON.stringify(parsed));
}

export function decodeSessionCursor(value: string): UserSessionCursor {
  const json = base64UrlDecode(value);
  return sessionCursorSchema.parse(JSON.parse(json));
}

function appendSearchText(existing: string, message: string): string {
  return [existing, normalizeText(message)]
    .filter(Boolean)
    .join('\n')
    .slice(-MAX_SEARCH_TEXT_LENGTH);
}

function normalizeText(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function toSessionSummary(row: SessionRow): UserSessionSummary {
  return {
    conversationId: row.conversation_id,
    title: row.title,
    latestMessagePreview: row.latest_message_preview,
    lastRunId: row.last_run_id,
    runCount: row.run_count,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function base64UrlEncode(value: string): string {
  const bytes = new TextEncoder().encode(value);
  let binary = '';
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/u, '');
}

function base64UrlDecode(value: string): string {
  const base64 = value.replaceAll('-', '+').replaceAll('_', '/');
  const padded = base64.padEnd(Math.ceil(base64.length / 4) * 4, '=');
  const binary = atob(padded);
  return new TextDecoder().decode(Uint8Array.from(binary, (character) => character.charCodeAt(0)));
}
